# Generated by Django 2.0.2 on 2018-06-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=30, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('productcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rewardpoint', models.CharField(max_length=30, null=True)),
                ('availability', models.CharField(max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Category')),
            ],
        ),
    ]
